version: "3.3"

services:

  app:
    image: biodepot/novnc-cynetworkbma:latest
    expose:
      - 6080
    networks:
      trial:
    volumes:
      - /home/jgockley/networktracing:/home/jgockley/networktracing
    ports:
      - "6080:6080"
    depends_on:
      - "caddy"
    environment:
      - APP_USERNAME=$USER
      - APP_PASSWORD_HASH=$HASH

  rstudio:
    image: network
    volumes:
      - /home/jgockley/networktracing:/home/jgockley/networktracing
    ports:
      - "8787:8787"
    environment:
      - USER=$USER
      - PASSWORD=$PASS

  caddy:
    image: cyto-caddy:latest
    networks:
      trial:
      outside-world:
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile 
      - /home/jgockley/networktracing:/home/jgockley/networktracing
    ports:
      - "6080:6080"
    environment:
      - APP_USERNAME=$USER
      - APP_PASSWORD_HASH=$HASH
      - name=networktracing_app_1
      - net=trial
      - reverse_proxy_from=app:6080

networks:
  trial:
    internal: true
  outside-world:
